"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const controller = require("../controllers/account.controller");
const uploadImageHelper = require("../../../../helpers/uploadImage");
const { role } = require("../../../../middleware/auth.middleware");
router.get("/", role("admin"), controller.index);
router.patch("/change-status/:status/:id", role("admin"), controller.changeStatus);
router.patch("/change-multi", role("admin"), controller.changeMulti);
router.post("/create", role("admin"), uploadImageHelper.single("image"), controller.create);
router.get("/detail/:slug", role("admin"), controller.detail);
router.patch("/edit/:slug", role("admin"), uploadImageHelper.single("image"), controller.edit);
router.patch("/delete/:id", role("admin"), controller.delete);
router.patch("/reset-password/:slug", role("admin"), controller.resetPassword);
router.get("/profile", controller.profile);
module.exports = router;
