"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const controller = require("../controllers/account.controller");
const uploadImageHelper = require("../../../../helpers/uploadImage");
const { validateAccount, validateResetPassword } = require("../../../../middleware/validate.middleware");
router.get("/", controller.index);
router.patch("/change-status/:status/:id", controller.changeStatus);
router.patch("/change-multi", controller.changeMulti);
router.post("/create", uploadImageHelper.single("image"), validateAccount, controller.create);
router.get("/detail/:slug", controller.detail);
router.patch("/edit/:slug", uploadImageHelper.single("image"), validateAccount, controller.edit);
router.patch("/delete/:id", controller.delete);
router.patch("/reset-password/:slug", validateResetPassword, controller.resetPassword);
router.get("/profile", controller.profile);
module.exports = router;
