"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const controller = require("../controllers/auth.controller");
const { validateLogin } = require("../../../../middleware/validate.middleware");
router.post("/login", validateLogin, controller.login);
router.post("/refresh", controller.refresh);
router.post("/verify", controller.verify);
router.post("/logout", controller.logout);
module.exports = router;
