"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const controller = require("../controllers/category.controller");
const { validateCategory } = require("../../../../middleware/validate.middleware");
router.get("/", controller.index);
router.patch("/change-status/:status/:id", controller.changeStatus);
router.patch("/change-multi", controller.changeMulti);
router.patch("/delete/:id", controller.delete);
router.post("/create", validateCategory, controller.create);
router.get("/:slug", controller.getBySlug);
router.patch("/edit/:slug", validateCategory, controller.edit);
module.exports = router;
