"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const controller = require("../controllers/auth.controller");
router.post("/register", controller.register);
router.post("/loginWithPassword", controller.loginWithPassword);
router.post("/refresh", controller.refresh);
router.post("/verify", controller.verify);
router.post("/logout", controller.logout);
module.exports = router;
