"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const controller = require("../controllers/order.controller");
const { validateCheckout } = require("../../../../middleware/validate.middleware");
router.get("/", controller.index);
router.post("/create", validateCheckout, controller.create);
router.get("/detail/:orderCode", controller.detail);
router.get("/user/:email", controller.getOrdersByUser);
router.post("/rentals/create", validateCheckout, controller.createRental);
module.exports = router;
